name: Publish to npm

on:
  push:
    branches: [ main ]  # Change to 'master' if your default branch is master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'  # Replace with your Node.js version
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci  # Clean install dependencies (faster than npm install)

       # Optional: Run tests before publishing

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Required for npm publish